deployment:
  imageURL: 989088456804.dkr.ecr.us-east-1.amazonaws.com/roboshop/catalogue
  imageVersion: 1.0.0

hpa:
  maxReplicas: 10
  utilization: 75

configMap:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"